apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smartsupport-data
  labels:
    app: smartsupport
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
